version: '3.8'

services:
  db:
    container_name: db_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_usr
      - POSTGRES_PASSWORD=postgres_db
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    container_name: web_container
    build: dev
    command: uvicorn dev.main:app --reload --host=0.0.0.0 --port=8000
    volumes: 
    - .:/prod
    ports: 
    - '8000:8000'
    restart: always
    depends_on:
      - db
volumes:
  db:
    driver: local